// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parser.Serviсes.Models.Context;

#nullable disable

namespace Parser.Serviсes.Migrations
{
    [DbContext(typeof(MetalContext))]
    [Migration("20220306235738_AddNewData")]
    partial class AddNewData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"), 1L, 1);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gosts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentShop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfPackaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfRollingStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WagonNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificateId");

                    b.HasIndex("ProductId");

                    b.ToTable("Certificate");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.ChemicalComposition", b =>
                {
                    b.Property<int>("ChemicalCompositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChemicalCompositionId"), 1L, 1);

                    b.Property<double?>("Al")
                        .HasColumnType("float");

                    b.Property<double?>("AlWithN2")
                        .HasColumnType("float");

                    b.Property<double?>("As")
                        .HasColumnType("float");

                    b.Property<double?>("C")
                        .HasColumnType("float");

                    b.Property<double?>("Cev")
                        .HasColumnType("float");

                    b.Property<double?>("Cr")
                        .HasColumnType("float");

                    b.Property<double?>("Cu")
                        .HasColumnType("float");

                    b.Property<double?>("Mn")
                        .HasColumnType("float");

                    b.Property<double?>("Mo")
                        .HasColumnType("float");

                    b.Property<double?>("N2")
                        .HasColumnType("float");

                    b.Property<double?>("Ni")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("P")
                        .HasColumnType("float");

                    b.Property<double?>("S")
                        .HasColumnType("float");

                    b.Property<double?>("Si")
                        .HasColumnType("float");

                    b.Property<double?>("Ti")
                        .HasColumnType("float");

                    b.Property<double?>("V")
                        .HasColumnType("float");

                    b.Property<double?>("W")
                        .HasColumnType("float");

                    b.HasKey("ChemicalCompositionId");

                    b.ToTable("ChemicalComposition");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.ImpactStrength", b =>
                {
                    b.Property<int>("ImpactStrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImpactStrengthId"), 1L, 1);

                    b.Property<double?>("AfterMechAgeing")
                        .HasColumnType("float");

                    b.Property<double?>("AfterMechAgeing1")
                        .HasColumnType("float");

                    b.Property<double?>("KCU")
                        .HasColumnType("float");

                    b.Property<double?>("KCU1")
                        .HasColumnType("float");

                    b.Property<double?>("KCV")
                        .HasColumnType("float");

                    b.Property<double?>("KCV1")
                        .HasColumnType("float");

                    b.HasKey("ImpactStrengthId");

                    b.ToTable("ImpactStrengths");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"), 1L, 1);

                    b.Property<string>("Banding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brinel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryOfDrawing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cementite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CertificateId")
                        .HasColumnType("int");

                    b.Property<int?>("ChemicalCompositionId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corrosion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerItemNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decarburiization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectOfTestPicses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Elongation")
                        .HasColumnType("float");

                    b.Property<string>("Eriksen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flatness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrainSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupCode")
                        .HasColumnType("int");

                    b.Property<string>("Hardness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Heat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImpactStrengthId")
                        .HasColumnType("int");

                    b.Property<double?>("KoafNavodorag")
                        .HasColumnType("float");

                    b.Property<double?>("MicroBallCem")
                        .HasColumnType("float");

                    b.Property<double?>("N90")
                        .HasColumnType("float");

                    b.Property<string>("NamberConsignmentPackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfClientMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderPosition")
                        .HasColumnType("int");

                    b.Property<string>("PattemCutting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("R90")
                        .HasColumnType("float");

                    b.Property<string>("Rockwell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RollingAccuracy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roughness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<double?>("SphericalHoleDepth")
                        .HasColumnType("float");

                    b.Property<string>("StateOfMatirial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StrengthGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurfaceQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TemporalResistance")
                        .HasColumnType("float");

                    b.Property<string>("TensilePoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrimOfEdge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitTemporaryResistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitYieldStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variety")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WeightId")
                        .HasColumnType("int");

                    b.Property<string>("Weldability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YieldPoint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("ChemicalCompositionId");

                    b.HasIndex("ImpactStrengthId");

                    b.HasIndex("SizeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WeightId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Labeling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"), 1L, 1);

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Thickness")
                        .HasColumnType("float");

                    b.Property<double?>("Width")
                        .HasColumnType("float");

                    b.HasKey("SizeId");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"), 1L, 1);

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Weight", b =>
                {
                    b.Property<int>("WeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeightId"), 1L, 1);

                    b.Property<double?>("Gross")
                        .HasColumnType("float");

                    b.Property<double?>("Gross2")
                        .HasColumnType("float");

                    b.Property<double?>("Net")
                        .HasColumnType("float");

                    b.HasKey("WeightId");

                    b.ToTable("Weight");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Certificate", b =>
                {
                    b.HasOne("Parser.Serviсes.Models.CertificateModel.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Package", b =>
                {
                    b.HasOne("Parser.Serviсes.Models.CertificateModel.Certificate", "Certificate")
                        .WithMany("Packages")
                        .HasForeignKey("CertificateId");

                    b.HasOne("Parser.Serviсes.Models.CertificateModel.ChemicalComposition", "ChemicalComposition")
                        .WithMany()
                        .HasForeignKey("ChemicalCompositionId");

                    b.HasOne("Parser.Serviсes.Models.CertificateModel.ImpactStrength", "ImpactStrength")
                        .WithMany()
                        .HasForeignKey("ImpactStrengthId");

                    b.HasOne("Parser.Serviсes.Models.CertificateModel.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.HasOne("Parser.Serviсes.Models.CertificateModel.Status", "Status")
                        .WithMany("Packages")
                        .HasForeignKey("StatusId");

                    b.HasOne("Parser.Serviсes.Models.CertificateModel.Weight", "Weight")
                        .WithMany()
                        .HasForeignKey("WeightId");

                    b.Navigation("Certificate");

                    b.Navigation("ChemicalComposition");

                    b.Navigation("ImpactStrength");

                    b.Navigation("Size");

                    b.Navigation("Status");

                    b.Navigation("Weight");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Certificate", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Parser.Serviсes.Models.CertificateModel.Status", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
